export const TOGGLE_FILTER_CARD = "filter/TOGGLE_FILTER_CARD"
export const TOGGLE_TOBE_DONE = "filter/TOGGLE_TOBE_DONE"
export const TOGGLE_IN_PROGRESS = "filter/TOGGLE_IN_PROGRESS"
export const TOGGLE_COMPLETED = "filter/TOGGLE_COMPLETED"
export const FILTER_ASC = "filter/FILTER_ASC"
export const FILTER_DESC = "filter/FILTER_DESC"
export const CLEAR_FILTER = "filter/CLEAR_FILTER"

export const GET_QARS_REQUEST = "qar/GET_QARS_REQUEST"
export const GET_QARS_REQUEST_SUCCESS = "qar/GET_QARS_REQUEST_SUCCESS"
export const GET_QARS_REQUEST_FAILURE = "qar/GET_QARS_REQUEST_FAILURE"

export const UPSERT_QAR_REQUEST = "qar/UPSERT_QAR_REQUEST"
export const UPSERT_NEW_QAR_REQUEST = "qar/UPSERT_NEW_QAR_REQUEST"
export const UPSERT_QAR_REQUEST_SUCCESS = "qar/UPSERT_QAR_REQUEST_SUCCESS"
export const UPSERT_QAR_REQUEST_FAILURE = "qar/UPSERT_QAR_REQUEST_FAILURE"

export const QARS_SYNCHED = "qar/QARS_SYNCHED"
export const QAR_SLOW_OR_OFFLINE = "qar/QAR_SLOW_OR_OFFLINE"

export const QAR_UPDATE_STATUS_REQUEST = "qar/QAR_UPDATE_STATUS"
export const QAR_UPDATE_STATUS_REQUEST_SUCCESS = "qar/QAR_UPDATE_STATUS_SUCCESS"
export const QAR_UPDATE_STATUS_REQUEST_FAILURE = "qar/QAR_UPDATE_STATUS_FAILURE"