export const DEVICE_LOCATION_REQUEST = "user/DEVICE_LOCATION_REQUEST"
export const DEVICE_LOCATION_REQUEST_SUCCESS = "user/DEVICE_LOCATION_REQUEST_SUCCESS"
export const DEVICE_LOCATION_REQUEST_FAILURE = "user/DEVICE_LOCATION_REQUEST_FAILURE"


export const LOGIN_REQUEST = "user/LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESS = "user/LOGIN_REQUEST_SUCCESS"
export const LOGIN_REQUEST_FAILURE = "user/LOGIN_REQUEST_FAILURE"

export const SIGNUP_REQUEST = "user/SIGNUP_REQUEST"
export const SIGNUP_REQUEST_SUCCESS = "user/SIGNUP_REQUEST_SUCCESS"
export const SIGNUP_REQUEST_FAILURE = "user/SIGNUP_REQUEST_FAILURE"
export const CLOSE_MODAL = "user/CLOSE_MODAL"
export const SHOW_MODAL = "user/SHOW_MODAL"

export const SET_EQUIPMENT_REQUEST = "user/SET_EQUIPMENT_REQUEST"
export const SET_EQUIPMENT_REQUEST_FAILURE = "user/SET_EQUIPMENT_REQUEST_FAILURE"

export const UPDATE_USER_INFO_REQUEST = "user/UPDATE_USER_INFO_REQUEST"
export const UPDATE_USER_INFO_REQUEST_SUCCESS = "user/UPDATE_USER_INFO_REQUEST_SUCCESS"
export const UPDATE_USER_INFO_REQUEST_FAILURE = "user/UPDATE_USER_INFO_REQUEST_FAILURE"

export const FETCH_FIELD_TECHS_REQUEST = "user/FETCH_FIELD_TECHS_REQUEST"
export const FETCH_FIELD_TECHS_REQUEST_SUCCESS = "user/FETCH_FIELD_TECHS_REQUEST_SUCCESS"
export const FETCH_FIELD_TECHS_REQUEST_FAILURE = "user/FETCH_FIELD_TECHS_REQUEST_FAILURE"

export const UPDATE_USER_TOKEN_REQUEST = "user/UPDATE_USER_TOKEN_REQUEST"
export const UPDATE_USER_TOKEN_REQUEST_SUCCESS = "user/UPDATE_USER_TOKEN_REQUEST_SUCCESS"
export const UPDATE_USER_TOKEN_REQUEST_FAILURE = "user/UPDATE_USER_TOKEN_REQUEST_FAILURE"

export const UPSERT_USER_PASSWORD_REQUEST = "user/UPSERT_USER_PASSWORD_REQUEST"
export const UPSERT_USER_PASSWORD_REQUEST_SUCCESS = "user/UPSERT_USER_PASSWORD_REQUEST_SUCCESS"
export const UPSERT_USER_PASSWORD_REQUEST_FAILURE = "user/UPSERT_USER_PASSWORD_REQUEST_FAILURE"

export const GET_USER_BY_ID_REQUEST = "user/GET_USER_BY_ID_REQUEST"
export const GET_USER_BY_ID_REQUEST_SUCCESS = "user/GET_USER_BY_ID_REQUEST_SUCCESS"
export const GET_USER_BY_ID_REQUEST_FAILURE = "user/GET_USER_BY_ID_REQUEST_FAILURE"

export const CREATE_QAR_USER_REQUEST = "user/CREATE_QAR_USER_REQUEST"
export const CREATE_QAR_USER_REQUEST_SUCCESS = "user/CREATE_QAR_USER_REQUEST_SUCCESS"
export const CREATE_QAR_USER_REQUEST_FAILURE = "user/CREATE_QAR_USER_REQUEST_FAILURE"

export const USER_SLOW_OR_OFFLINE = "user/USER_SLOW_OR_OFFLINE"
export const USER_SYNCHED = "user/USER_SYNCHED"

export const SEND_NOTIFICATION = "user/SEND_NOTIFICATION"

export const OFFLINE = "device/OFFLINE";
export const ONLINE = "device/ONLINE";

export const RESET_USER_STATE = "user/RESET_USER_STATE"
export const RESET_ERROR = "user/RESET_ERROR"

export const SHOW_CONFIRM_ALERT = "user/SHOW_CONFIRM_ALERT"
export const CLOSE_CONFIRM_ALERT = "user/CLOSE_CONFIRM_ALERT"

export const SHOW_COUNTRY_MODAL = "user/SHOW_COUNTRY_MODAL"
export const CLOSE_COUNTRY_MODAL = "user/CLOSE_COUNTRY_MODAL"
export const PHONE_VALID = "user/PHONE_VALID"
export const NEW_QAR_PHONE_VALID = "user/NEW_QAR_PHONE_VALID"
export const FULLNAME_VALID = "user/FULLNAME_VALID"
export const FULLNAME_EDIT_VALID = "user/FULLNAME_EDIT_VALID"
export const PASSWORD_VALID = "user/PASSWORD_VALID"
export const PASSWORD_EDIT_VALID = "user/PASSWORD_EDIT_VALID"
export const EMAIL_VALID = "user/EMAIL_VALID"
export const EMAIL_EDIT_VALID = "user/EMAIL_EDIT_VALID"
export const USER_NOT_FOUND = "user/USER_NOT_FOUND"
export const USER_NOT_SIGNED_UP = "user/USER_NOT_SIGNED_UP"
export const INVALID_CREDENTIALS = "user/INVALID_CREDENTIALS"
export const PASSWORD_CONFIRMATION = "user/PASSWORD_CONFIRMATION"
export const PASSWORD_EDIT_CONFIRMATION = "user/PASSWORD_EDIT_CONFIRMATION"
export const EMAIL_NOT_FOUND = "user/EMAIL_NOT_FOUND"
export const OLD_PASSWORD_INCORRECT = "user/OLD_PASSWORD_INCORRECT"

export const CHECK_ACCOUNT_AVAILABILITY = "user/CHECK_ACCOUNT_AVAILABILITY"
export const USER_ACCOUNT_NOT_AVAILABLE = "user/USER_ACCOUNT_NOT_AVAILABLE"
export const USER_ACCOUNT_AVAILABLE = "user/USER_ACCOUNT_AVAILABLE"
export const CHECK_ACCOUNT_VERIFICATION_STATUS = "user/CHECK_ACCOUNT_VERIFICATION_STATUS"
export const VERIFY_EXISTING_ACCOUNT = "user/VERIFY_EXISTING_ACCOUNT"
export const USER_ACCOUNT_VERIFIED = "user/USER_ACCOUNT_VERIFIED"
export const NO_ACCOUNT_WITH_PROVIDED_PHONE_NUMBER = "user/NO_ACCOUNT_WITH_PROVIDED_PHONE_NUMBER"
export const USER_ACCOUNT_VERIFICATION_STATUS_CHECK_FAILURE = "user/USER_ACCOUNT_VERIFICATION_STATUS_CHECK_FAILURE"
export const OTP_VALIDATE = "user/OTP_VALIDATE"
export const OTP_SEND_REQUEST = "user/OTP_SEND_REQUEST"
export const OTP_SEND_SUCCESS = "user/OTP_SEND_SUCCESS"
export const OTP_SEND_FAILURE = "user/OTP_SEND_FAILURE"
export const OTP_SEND_STATUS_RESET = "user/OTP_SEND_STATUS_RESET"
export const OTP_SEND_ERROR = "user/OTP_SEND_ERROR"
export const OTP_VERIFY_REQUEST = "user/OTP_VERIFY_REQUEST"
export const OTP_VERIFY_SUCCESS = "user/OTP_VERIFY_SUCCESS"
export const OTP_VERIFY_STATUS_RESET = "user/OTP_VERIFY_STATUS_RESET"
export const OTP_VERIFY_FAILURE = "user/OTP_VERIFY_FAILURE"
export const OTP_VERIFY_ERROR = "user/OTP_VERIFY_ERROR"
export const SHOW_PHONE_VERIFICATION_MODAL = "user/SHOW_PHONE_VERIFICATION_MODAL"
export const CLOSE_PHONE_VERIFICATION_MODAL = "user/CLOSE_PHONE_VERIFICATION_MODAL"
export const RESET_ACCOUNT_AVAILABILITY = "user/RESET_ACCOUNT_AVAILABILITY"
export const RESET_ACCOUNT_VERIFICATION_STATUS = "user/RESET_ACCOUNT_VERIFICATION_STATUS"
