export const GET_QAP_DATA_BY_QAR_ID_REQUEST = "qap_data/GET_QAP_DATA_BY_QAR_ID_REQUEST"
export const GET_QAP_DATA_BY_QAR_ID_REQUEST_SUCCESS = "qap_data/GET_QAP_DATA_BY_QAR_ID_REQUEST_SUCCESS"
export const GET_QAP_DATA_BY_QAR_ID_REQUEST_FAILURE = "qap_data/GET_QAP_DATA_BY_QAR_ID_REQUEST_FAILURE"

export const UPSERT_QAP_DATA_REQUEST = "qap_data/UPSERT_QAP_DATA_REQUEST"
export const UPSERT_QAP_DATA_REQUEST_SUCCESS = "qap_data/UPSERT_QAP_DATA_REQUEST_SUCCESS"
export const UPSERT_QAP_DATA_REQUEST_FAILURE = "qap_data/UPSERT_QAP_DATA_REQUEST_FAILURE"


export const UPLOAD_QAP_DATA_REQUEST = "qap_data/UPLOAD_QAP_DATA_REQUEST"

export const CREATE_QAP_DATA_REQUEST = "qap_data/CREATE_QAR_QAP_DATA_REQUEST"
export const CREATE_QAP_DATA_REQUEST_SUCCESS = "qap_data/CREATE_QAR_QAP_DATA_REQUEST_SUCCESS"
export const CREATE_QAP_DATA_REQUEST_FAILURE = "qap_data/CREATE_QAR_QAP_DATA_REQUEST_FAILURE"

export const QAP_DATA_SLOW_OR_OFFLINE = "qap_data/QAP_DATA_SLOW_OR_OFFLINE"
export const QAP_DATA_SYNCED = "qap_data/QAP_DATA_SYNCED"